# Generated by Django 4.2.6 on 2024-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_ai_application_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/book_covers/"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="sample",
            field=models.FileField(
                blank=True, null=True, upload_to="media/book_samples/"
            ),
        ),
    ]
