# Generated by Django 4.2.6 on 2024-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_ai_application_dashboard", "0003_book_book_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="number_of_times_read",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
