# Generated by Django 4.2.6 on 2024-05-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_ai_application_dashboard", "0004_book_number_of_times_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendedBookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_category",
                    models.CharField(
                        help_text="The contributor's first name or names.",
                        max_length=1050,
                    ),
                ),
                (
                    "book_distributors",
                    models.CharField(
                        help_text="The contributor's last name or names.",
                        max_length=1050,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendedBookPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the Publisher.", max_length=50
                    ),
                ),
                ("website", models.URLField(help_text="The Publisher's website.")),
                (
                    "email",
                    models.EmailField(
                        help_text="The Publisher's email address.", max_length=254
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The title of the book.", max_length=70),
                ),
                (
                    "publication_date",
                    models.DateField(verbose_name="Date the book was published."),
                ),
                (
                    "isbn",
                    models.CharField(
                        max_length=20, verbose_name="ISBN number of the book."
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/book_covers/"
                    ),
                ),
                (
                    "sample",
                    models.FileField(
                        blank=True, null=True, upload_to="media/book_samples/"
                    ),
                ),
                ("book_details", models.TextField(blank=True, null=True)),
                ("number_of_times_read", models.IntegerField(blank=True, null=True)),
                (
                    "book_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_app_root_ai_application_dashboard.recommendedbookcategory",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_app_root_ai_application_dashboard.recommendedbookpublisher",
                    ),
                ),
            ],
        ),
    ]
