# Generated by Django 4.2.11 on 2024-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_security_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
