# Generated by Django 4.2.6 on 2024-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_security_user", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_encoding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
